Ticket #23262 - Add create extension commands to dbmanager script

diff --git a/fred-dbmanager.in b/fred-dbmanager.in
--- a/fred-dbmanager.in
+++ b/fred-dbmanager.in
@@ -127,6 +127,18 @@ host @DBNAME@ @DBUSER@ @CIDRIPV6@ @METHOD@ \
             echo -e "Unable to create extension pgcrypto. Installation terminated.\nError message: $error_msg"
             exit 1
         fi
+        error_msg=$(( echo "CREATE EXTENSION pg_trgm" | @PGBINDIR@/psql @DBNAME@ -p @DBPORT@ ) 2>&1 | grep "ERROR" )
+        if [ "$error_msg" != "" ]
+        then
+            echo -e "Unable to create extension pg_trgm. Installation terminated.\nError message: $error_msg"
+            exit 1
+        fi
+        error_msg=$(( echo "CREATE EXTENSION unaccent" | @PGBINDIR@/psql @DBNAME@ -p @DBPORT@ ) 2>&1 | grep "ERROR" )
+        if [ "$error_msg" != "" ]
+        then
+            echo -e "Unable to create extension unaccent. Installation terminated.\nError message: $error_msg"
+            exit 1
+        fi
         error_msg=$(( @PGBINDIR@/psql @DBNAME@ -U @DBUSER@ -f $STRUCTSQL -p @DBPORT@ ) 2>&1 | grep "ERROR" )
         if [ "$error_msg" != "" ]; then
             echo -e "There are errors in SQL script file $STRUCTSQL. Installation terminated.\nError message: $error_msg"
