show error message, when sql commands goes wrong as requested in #4670 and #4648
git-svn-id: file:///data/svn/enum/db/trunk@16719 b60c293d-5e0d-0410-87b2-fb9704ccd4b5

diff --git a/fred-dbmanager.in b/fred-dbmanager.in
--- a/fred-dbmanager.in
+++ b/fred-dbmanager.in
@@ -119,7 +119,11 @@ host @DBNAME@ @DBUSER@ @CIDRIPV6@ @METHOD@ \
                             -p @DBPORT@ > /dev/null 2>&1
         @PGBINDIR@/createlang plpgsql @DBNAME@ \
                               -p @DBPORT@ > /dev/null 2>&1
-        @PGBINDIR@/psql @DBNAME@ -U @DBUSER@ -f $STRUCTSQL -p @DBPORT@ >/dev/null 2>&1
+        error_msg=$(( @PGBINDIR@/psql @DBNAME@ -U @DBUSER@ -f $STRUCTSQL -p @DBPORT@ ) 2>&1 | grep "ERROR" )
+	if [ "$error_msg" != "" ]; then
+	    echo -e "There are errors in SQL script file $STRUCTSQL. Installation terminated.\nError message: $error_msg"
+	    exit 1
+	fi
     fi
 }
 
